### ISSUE TITLE
Using an outdated version of k6

### ISSUE THREAD

**Issue by nicholaspshaw** [LeonAdato/xk6-output-statsd#10]
The current dependency is v0.45.1 with the latest version of k6 being v0.50.0

Is this going to be updated at any point?  Between xk6, this extension and recent changes, k6 browser based tests are broken for me. (though I'm not suggesting an update with fix this)

**Comment by kempsterc** [comment]
I have created this PR here https://github.com/LeonAdato/xk6-output-statsd/pull/11

**Comment by kempsterc** [comment]
@nicholaspshaw 
PR for latest version is merged
