### ISSUE TITLE
Porting a know issues from the k6 repository

### ISSUE THREAD

**Issue by olegbespalov** [LeonAdato/xk6-output-statsd#18]
# What?

There are a couple of opened issues in the k6 repository related to the StatsD output:

* https://github.com/grafana/k6/issues/2980
* https://github.com/grafana/k6/issues/2819
* https://github.com/grafana/k6/issues/2776
* https://github.com/grafana/k6/issues/2549
* https://github.com/grafana/k6/issues/2527
* https://github.com/grafana/k6/issues/2470
* https://github.com/grafana/k6/issues/2044

Since we likely won't work on them, keeping in mind the https://github.com/grafana/k6/issues/2982 it's good to port (not sure of transfer could work) to this repository since currently this is the primarily recommended repository for the k6's statsd output.

@LeonAdato, do you think that makes sense? If so, I could port the mentioned issues to the repo and close them in the k6 reposory

**Comment by javaducky** [comment]
Thanks @olegbespalov (and hope you and the rest of the team are well!).

Porting the issues to this repository makes sense to me. Would you concur @LeonAdato ?

We'll be watching for https://github.com/grafana/k6/pull/3849 to remove StatsD from k6.

**Comment by LeonAdato** [comment]
Ported and merged into the 0.2.0 version.

**Comment by olegbespalov** [comment]
Hi @javaducky @LeonAdato !

Thanks a lot for taking care! 

@javaducky, we're good! Hope everything is good too on your side :relaxed: 

@LeonAdato, out of curiosity, where were the issues ported? I can't see them https://github.com/LeonAdato/xk6-output-statsd/issues. I'm asking for details to mention the ported issue while I'm closing issues in k6's repository for better visibility.

**Comment by LeonAdato** [comment]
I mis-spoke. I just updated the repo based on the latest K6 which fixed a bunch of lingering issues. I'll get those open issues ported over in the next few days.

**Comment by olegbespalov** [comment]
@LeonAdato, I see that you've commented on each individual issue; I believe you intended to ask issues' authors to port them (unfortunately, there is no way to transfer issues between GH organizations). 

But since we're not sure if all the authors track the issues, and if that's fine by you, I could open them and link by myself. 

Does that sound good?

**Comment by LeonAdato** [comment]
Sounds great!
